apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+p5f5U2mgN5T5wmT+o15XXzxS7C0upq6uJ2ZwG+RVIr/5g==,iv:yC2AUsqDr2qUJA/CRhN5AaqCvpEytib4D0YEW3jQNkc=,tag:lEe7g6aCxInVshYOTJtwfg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:HIfyiWrqE3Hx5HyLbKElcyJ+Aw9Axng2DTjvNb8s2nDB73RQ6g==,iv:y/8KvRdOv3/+YCORgk9N10bJGFUlEGrXmeyuWCk0lCU=,tag:WI0iKmzVJI6HtnXK0GWGng==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:CJc9hCsqs7tJjg/xpIN0,iv:WJngs1FLyybDfSuV0qxuW3yBQDwuWaoxrY5wSk9SlKs=,tag:DvAr8OOM+20xQybETcpHiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSks5Y2hmRG9pUCtQdURN
            bWFIS2k2elpxU3h2Y29Id05QM29CanlyTkgwCi9PZEVxNXREZDlNSXVZc0dUVE5o
            TUc4ZytCK2NFemdNY2I5dThBNU5TNVEKLS0tIG4veVJGdGJCUW1CbDg2UzhKZWJk
            a3YrYVFEaHRnaG1CN1FVdS9QYklMZGMKT3OeuybH5jOdkKzjeWoJ/mx0XI1dnDs8
            9QpmDqNTmJS7fn8z0CDZvNvHMOfKvbaDuz9jRDS3AhBe5TLCMX1n9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T23:11:20Z"
    mac: ENC[AES256_GCM,data:535WagqT08c6T0P8XsPsmyCkYz0pRjU3Uz3cq/vzQPWjpRrYoRuwEBzOvjiLAcRQxNZlSFPW6/W0KCWzinOZ+LJ20s7ghGiHT6wdYAf0grdadCdT9Q+g0zz+gqPr+BHEmoMbtaRAnG7DVG2Ou9w11c0ran+kEKsNyOHXKFe2z6o=,iv:Adj65o+0yruy1aCuhXf9HE+MUYMB+XBsIpHXG6nolTg=,tag:eh5PiEH4B5oGg4pafqZuaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
