kind: ENC[AES256_GCM,data:8aaZl3GP,iv:PzlWdbHSOagWrbqHjXO5velENPyZjr8ScVMRe+BexU4=,tag:+aBQVl1Wpw0BLNpBubsShQ==,type:str]
ansible_user: ENC[AES256_GCM,data:Zb6i8yZN,iv:+18a3lX/qv49alQ6MUGZiJXafiFKqKMDIyVWi73WXAg=,tag:QzUp941FlgJ4KF5FKAjGyg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nY4cVuU9LwB49XUfvu8WrA==,iv:SXU8s4YDZWvkav1XDidiu+kraosbay+rGvG9Opr/5a8=,tag:AuZuKRmWt35r9FIis8Rc7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNmw5a0Zza0VnM3FZelNi
            YlE1TW93dFBoRzREVWhjcGUyVEZrNlhUYkg0CkR4TnRMOU1nelNvM2h2azk4R21y
            czZxL3NSTi9BR3hLTnZqTldOQmR5OFkKLS0tIHVXU1dnTXhkVTBBOFhReXlZMnJq
            bDMvb2o1OU5hMzJWNUQ3Yk04RCt3TGcKzXjn5iurZZXSzcgPYX2YhZq5f8IonUGu
            ZwoRHzMMq5epVuR/zMOhiP2bMzxKF3zi3AyCzJ8NdQawOuiH4SiCuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T23:11:20Z"
    mac: ENC[AES256_GCM,data:2K9mPlWLenRs+Soteo3wBPCXMutn8OBmQaM9E/Kb63XyrpJoQM9iGCJiB+9vFAHdYgqJNu88b+Y6U8KETVEIdmP8NHNc+nOAP1ZcIW1dBg0YyhCnerh1PwUXNyNaSxUubrR5sFT1qj0vVwM8XweiWgZgwB4APihpR1qeeQQuRCw=,iv:8kVONsR1m5H+rr9kVH8Ar9rPqkmDwoz0cDeDcELm+CI=,tag:OmP86SA5ScxgfSdrXYKknA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
