---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cloudflared-credentials
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: Cloudflare Tunnel - homeops
        property: credential
