---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: nextcloud-config
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: "${NFS_BASE_PATH}/config/nextcloud"
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name nextcloud
  namespace: cloud
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nextcloud-config
  resources:
    requests:
      storage: 5Gi
