---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud
resources:
  - nextcloud-secret.sops.yaml
  - config-pvc.yaml
  - nfs-pvc.yaml
  - helmrelease.yaml
patchesStrategicMerge:
  - patches/postgres.yaml
