apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tdkzwv4LMMeg0UL3Icao6A==,iv:Hfd7rRvJbmqW3zP6J+Gfru+Spxewpm6jFstp/IrSio0=,tag:++1HHQBcT1VaIkY48UTFKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMG1IMklkWit3MXFxNTRt
            Z2ZVSGtVVTBmL3hpYkFkalFpWDRteStWTXpnClBuazBRcEFKUWNEOGRzb3k1RVZp
            bW80bGVnazhLUHdhbHdvSkxpLy9aV1kKLS0tIDdNaHc5ay92N1JrVDIzNDRIbFBP
            RE5WNFhkanJKYW82ZUhiN1B1cG5lZHMKVK5s5nKydyY6T5oRMnf+vj3UZKDCMkSR
            O4nFv4AUpryNjI4vfQugxjplu7EQ7xX69UVaZTOSq1IzRZRWBCieYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T23:11:20Z"
    mac: ENC[AES256_GCM,data:OjWCXcykHsiNlENjh2gBmYM+gLAmbAmbibQ3fKu2tVmQcL8RyVkIkJjlQtoIJEm3w/4xhvrjLv+TSrVYExv3C8VgxFWfpvVnWyIr2V2ezUyRHseXVYq11/vuveccRzTBumDHkqX6UmjRfqbKJbEfM0oTmK6u5Nf5/2w00rG1+8A=,iv:e8vVMOrGx9YAyLi1ASdDv4nAhWlqJ0to/D+sQCTTQs0=,tag:6U7E7/vx067scm7WclV42g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
