---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cilium
  values:
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    k8sServiceHost: 127.0.0.1
    k8sServicePort: "7445"
    routingMode: native
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.244.0.0/22
    enableRuntimeDeviceDetection: true
    devices: ["eno1"]
    extraConfig:
      direct-routing-device: "eno1"
    bpf:
      masquerade: true
      preallocateMaps: true
    bpfClockProbe: true
    endpointRoutes:
      enabled: true
    ipam:
      mode: kubernetes
    gatewayAPI:
      enabled: false
    l2announcements:
      enabled: true
    k8sClientRateLimit:
      qps: 5
      burst: 10
    loadBalancer:
      algorithm: maglev
    socketLB:
      enabled: true
      hostNamespaceOnly: true
    localRedirectPolicy: true
    pmtuDiscovery:
      enabled: true
    bandwidthManager:
      enabled: true
      bbr: true
    enableIPv4BIGTCP: true
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
