apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:oCNfnorBQYICMXB0w+Eov4mKyqJyh/P9OjWRbgR3jdB6wP4leA==,iv:DPmi9o1gminMkxYlDnSYdEUF07s8nJQ6pC0giHLgnoU=,tag:8VS2piKRuAyneLI2dDp7ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNVg1Nmw4N2Y0RUk4VXda
            cUNxWDdqa2E2VDFxcVZXS2V5am1FRXRsYlVJCk11ZnMxaDFDMi9IOTNDanBtaGlm
            UTF4LzYwNHJrRTY1ZUdhK3A4aDBidjQKLS0tIGNmOExOMk9VdnlDOUtIMmxkWVdZ
            K1ZLVUpUdkp2MitKMTJIQlV3NGh0WTgKtj9LKZpWtvjsaMzDTb2Y9SRx1Ya0ILvv
            NQKqbSkeggqEAnbxMR9aYZUmyNghGBM8GGnOg7ssr8hD8jFD0NCJug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T23:11:20Z"
    mac: ENC[AES256_GCM,data:gf/en18FEDFUWINDu+Ik/azW8JwcMzmkqlpaeOvXeOCxoVGCbR90vI/LR5ppLmoXO0mjYi2Wn6cv+SRtDTq6Sr1/b7YOQgdYQXXSq/IWwFbpjiu+9oKXCcFmX3xMv9oxjWL6r94+wyE1MCdj5gh8wjfs0Y2HFzFXXi4RFPI481A=,iv:/kYuDK8YSt33HOsJ2mO7iqvPvPTJMJrkkTYEvYtpR+s=,tag:piGbKk3qqajo6IFdeltXTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
