apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:iYbdrIbiCJcopaDSG1iKlerMZ0DAx6NCd8qOL6Na0CdxDkkTDw==,iv:xz6jRY/Mr8A9edirpAhcKpCy/COvOPg6IFWJIEjWQUY=,tag:cPhgVJTnwMeDyjbdqbL7+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa2dQR2NPOFREampORjR3
            Vk5yQis0Tjl0ZVpGMnJFNlFMVzNzY1RpOVU4Cm1KWGkyUHZwRVZBYUFUWlZHaU9s
            V3RRNGJKU1pZVkFZS0xMMGtmNHo5MlUKLS0tIFNLZUlVRmdtUklzcTNiWjNMQ2RV
            b0N6a0V3M1ZuRm85WGFzNkZCMWxZeU0KkQNLXbylEBkzNMDYNrozebrR/1IEbbRR
            DubQ6855fwkbNGIYgdtFCaD0w1B9xBIitB6pPyoCiKj+0acUaUkhGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T22:10:13Z"
    mac: ENC[AES256_GCM,data:UpryBNFauT9xg8LKqxbHCUKqRGWFiWYVw6A4qVMIYsY92+yv7eRwXs4HkUYyqVb7WKBV7kLGT2yK3CPIBVPNMAbYmyeTh2Xm1kACDzFGtD06xOZxWC1w7gN+ndWxJ02FpKT62nIQvRMVh6b5XP8zhBHmzyk+WsMrPnvZvAuQB5I=,iv:o4vEa8HKYSmBZjNMfOkZ9oNuTn/alGj+X/uLPazMPVo=,tag:K2uJ6aOmhneKs5lxEwjHVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
