apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:CyJ89WDdUj+yOisfld1qbW1rIQPBVvrF415Tnus5nFuywg==,iv:PYYB2obI5QTrD8+WiE3+8rvp/NlzsGl7b7FTAjm/+0A=,tag:+GEzYedH6pAJFgCt5jzYzA==,type:str]
    api-key: ENC[AES256_GCM,data:FzXNeN8Nydbbx0x5asvxHf6m6pqI3r0A09TlwfI0rijWoCdZGg==,iv:6lRLLuZPOL9LHtaaDm0tKjVAPd8fzKoNvGLfKsAbje8=,tag:uCSxQ/q2o+yYDHZFOS1J4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvamUrUEE3VysvNS9QaXlK
            aUZyOGROU0RseDU4SDN1TzNyN2gzWWNiTzJrCkJwZzhCY2NCSXA3Y2ZqMC9vRFF6
            bnlpaWtjNSt5amxQK0NDZVVDMkxkWmcKLS0tIFpDZDhNTEY2RlpYeHUrR1F1ejNa
            Q0MvektCeFJnT2dGNnZ0aGFEdytINUUKQGymsZTxlzaKmjGJb8sfb37UIvS2Qa7m
            DLAqQiAggS873DJr2GAfDg+V696JJl/vCiMKrU4juFd8bpEo6L3GoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T21:26:42Z"
    mac: ENC[AES256_GCM,data:+BnwZ9KGJLJmWFUeP6r3WuIYvuLNZjC8juJx8q2GyGBgGPurI4bzLHtammKCnXolV06zMtyaxgpRk9Sm5v0+a2v/EOPfrVr8SN/nlGG7aCTt+gdohk0b3cN1i0MI02iHqp64HRdtBgdOlRFvy+AKnnX7Et+r9YoUcZgqzr+3DIM=,iv:6sxdb1hDLgpEBL6cFb4068fBoINJe1ng6y0Wv13jnG0=,tag:ujvqHx0/dKYUzx+exe6R/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
