apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Ag5eHGqOOh+Wb0e60vyQidXh/685V+QOYjzxAX+mBSvNcA==,iv:1ZFbGxQ15vtp8KH7E+g8YJtvH4wQZqSxWlvr7ggSnnQ=,tag:wr5F5oUDTOTn7etnflreLQ==,type:str]
    api-key: ENC[AES256_GCM,data:smPl2AgiXqkUfBhNFyZXavuS3QxZSeQowl4x4MkjPRTcmYzLiQ==,iv:hpg734SBVGnqPq1RHgoYZVaH3of/LALdZDgOVsS3Itw=,tag:0pJUzWNafZsVs73ndcCAkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNjRaUVNZaHl4MnNPZWwz
            UkV2akw4MjduYWVuSGRnZEVLV2RVaEdWZ3dzCjYrMW93QlY2V01HZ1k3T2lqcFlu
            Ym5uRGliV3lvZTc5dEFHWlhqYm9wZlUKLS0tIGd5L2RRRHJpOSsxYUY4Vkc4aTBC
            WlZXT1NvblltVmV5WFllZ1dCNlJXNjgKy//d+g+Z3XimuI/7sn3IGBMKyNgJ1asD
            FIVKO6BeGy+5GXqRco5yiUfN4Y9kAFfX/Mzjw+TCPTSGUE7bFwVJFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T22:10:13Z"
    mac: ENC[AES256_GCM,data:OJn66U1zETSLlP61OfIp7+4DiPMN9zwz4RgDJLnDzrZRsnExa/vI3NMLvrP6cicIj5OOBn2dxhBS0TpcAGc0A222GHwvYhs9TiCpWRhnsXf+aL0Bnu+/6upva1LMv4wPC6bqfmXIjCYvBrfhS58MunYlA+zX2ui76xfWJ3oLiUs=,iv:fJpT243Gld0pAly12PWSrH812Osk3ZmxKA6ObmqDStA=,tag:tRMWuJmHrgETMX3+y8dXyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
