apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5eBBT8Mw1jSuOiLFxrygPJpp5pM6Od0aFrbb+8+ywLztZf6AuH1v+RboJKsnwFAx9g+m2Ae+HDIrhSdOPMaXGRdPdpYUcQHCMGCGQ6Y5AqOXL/EJs5ExAz+FAU5KVZwTSC8zp3UurEn+tTxq3wP2VIeQyQjGqKN/Tz+ItWa7jDAVFu2IbWV5ZW6RudZYKNnJ/XtlKUlfQDCq74r7ygeVM9sL6tBNETzbx60lPO16/gIebfcwpoqY4Fw2/0kAYQnUvd/Iw22hUxcfqp4fhBNsIhCGYnKFLJh1OSO4p6hLBsdrlyGk4cE9zGeVqhW+CGP1B9L5ZVhKqhrYzP7doYh3IB5a7nfLY7DtgV/HTT6hrMAzw3IlNQdhNmMnqZWw104oglly8xOF5BM64hED0RxugzGhK9hjLVOriwVnGe4xZ3dWSAGfsqWvsp0cfrSVr+eCKjAQyuBfduC/IZCuflsKx34oRsXCK621E+yMi5ZFjtnP+zIIDZ7x02hHnzUBCJKM19DDlqIDNGikTDTWdOHYVCIdHW9FhAkLtjUpSu6z7rP11rZqLPrMOpYR8xBeDr0OkO/n3+5UZFFvt7NHti7D4xIPhmMwq1hJ21a++VPfyW6s25IaXcdVF6RCBBg3SHSnzVTDI4VSQKwmcvf5DD3AvGnNZw6P90D8DQ+/3jxJJdteY6zGyv35ZEPyzJKlZSXtY3kZ3lWOWfODtMAPjsWtFGU0tmAA6LaX/8Bc1LLAd+ckEHqBLs6byx/e8GSfApg4fVw9lCdQmO8WE+yWu+d4M7+3Ello7rmwoQRPtVGlH2ZXp3m7DX8DUP84fB+kDK3gvcF08x2i5NIqlCgMbrrEKc/j,iv:bgTOTklojvPVXd8SovpkBccr2dKxh8m2INTOcsj1JPk=,tag:H7ORrcJt4beNQUMuubrH5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdyszMW5qZVVSZm82ODdG
            Uk41Ty8vaS9jUWR0anJyZXBpSTZnQVdLVGlFCk9KR3Boai9EYVBVdXdHWEU1dEY0
            a1dacUdNUUpnUWdLaVlzTGlyS2VqWjAKLS0tIGVZREladHVhS0FpN2IrYWJ4VVJn
            UUlocFFrUlB3QmdVd09sTENvaU45WlEKmmnPBsmnFBEaE81Bv5HLuCdXJvMPt+Ag
            gc448XqPnQPy8YeTGWOTC/Tw7lP8BJoujz76JJ4R1cB8E7jeNmYzYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nc697vzzxu69ryr2da9awvzux0zu65xk2kq38ck23uf8ctt5v9s32vtc4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T19:47:29Z"
    mac: ENC[AES256_GCM,data:M71zlo2Btx0kbIdTv6CCuyK71ZnBtQ8fUuYFPUvSQtzKvKOdOjBvy123iohi9r8zYOOPAg1tVfimFjoS34EVFw93PpFmh1Ew/aUSLJt8yoZ7vowfUGkA1bdrg8NyL/FFlDM11AQXLawJPb99MoOewx7iIebnzrm2NwnolTbfuMI=,iv:EJsM1cdX3CDVMDOL2bX8fwztE4pqySwgiOEsf4NzT9o=,tag:F5TcXlIOzRzIL3Z70echAw==,type:str]
    version: 3.13.1
