apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:UiHRePr8iLgWofLjkZeVGF7JqVfo0SKFCC6VRjK91FTY/+DkKTgp99j32kQG4147HR93viKdh7NQKMoJcmUSugRyfpSubez9lFNYvemceeAN0ldmKEtSjvoA4WqMSiRc5rH1IXA2lWci/FEaHtFmgsX/mT61uLnOYKnrtUZoJVNcACRw4abyPhKkNKfpIQo7uWCYXUrFecXjDecuqTaB8nR+UxhUQQWHoPl0vAoAPLngiBn41dThwjdUgpY0/TXslQKTM29+k95kLimU1EdVmBn4aR2g9QWbEkvlk182ZkUKjZh0GbYaoLVyLYRMY9llTTdSZ58vx1CfnvquqFrS5kEibUC64AHC+LTIO4nMbsnmmA5CYPXFAVdq/xZ48dpXb2KdMFTc2GlKJnLpB+2i02PVypc4luEJvxnfybpd87P0nrZCl/LLFngwJeLZx4jqAOzDLv4lWHJe1QQyOlwmr9TqS//b4xiL/W90hrmJdaOiU+yfK9325Yjr3iL2sCjo2c7oRIQlAubXpGnp34AmbG39iuAdjNt5+//GPZsmgp5vNnc5TSvTOsJEd/oRnSorhJ+OLBJVuVxyLznk1AFj21YD7tJlPCNuoP4xPbYaLubq4Qzyjk5wNh9NdvIxdu0y1PNpD5jPaNbhbZ+lqrqbfK/yfAGzFrYFnYyZJwOTR8+10Xg5X9iF1d8BxwwG5MFWasOVnkS4cW8hJSAkyAFA0oeIlTvgg0m4HSV75McBjkGtATIVZHMYbGKoIMKAGrT3YLHHtrO9LxdFAUdRvGKR8islrmluHV5YvzuGvsVHW6GTSObFFKxYPEtOUVLT/yRXLI3qXs+TWDCfixDHJxjrgieF,iv:WAA0QwCvLhkE1vlIMCyhbV2ZSxR47nE/RCdtITp0ams=,tag:5+LPswMstBVRtW4LHrmrlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdyszMW5qZVVSZm82ODdG
            Uk41Ty8vaS9jUWR0anJyZXBpSTZnQVdLVGlFCk9KR3Boai9EYVBVdXdHWEU1dEY0
            a1dacUdNUUpnUWdLaVlzTGlyS2VqWjAKLS0tIGVZREladHVhS0FpN2IrYWJ4VVJn
            UUlocFFrUlB3QmdVd09sTENvaU45WlEKmmnPBsmnFBEaE81Bv5HLuCdXJvMPt+Ag
            gc448XqPnQPy8YeTGWOTC/Tw7lP8BJoujz76JJ4R1cB8E7jeNmYzYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nc697vzzxu69ryr2da9awvzux0zu65xk2kq38ck23uf8ctt5v9s32vtc4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T18:11:22Z"
    mac: ENC[AES256_GCM,data:ZM20XlDAxzlFaSmSRV4TyHQY37hdhF2Xe/AwXT/t7XW7tLFqvWI66RHBoPo3M8u7HAFD7Z4sO3M89Fy1aF4oIFKUSAKIyet1sa17KWUoBWqZTWff7oazzNSjwDuUfpdL1H5esyTWbWtjmf+HtU1D7ZxEbmaGvHdVATqLB8BORjo=,iv:2gcyrxeAyHyw5esDE2N+gHJl7Od+1y71n2DkAou4Heg=,tag:+lpOrAVZQZOWDqgUJuRnLw==,type:str]
    version: 3.13.1
