apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: backup
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:DePL3qQ=,iv:Jz1vvS5g1414Hx16djfa7yTkFAQM2acqiqu4DRburrM=,tag:OwuRWGn5YRRsFcOFGJeYkw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:GEOjRgymBCy/Tlwm7WXkYyVXs8pr7YJjHqVMcQKVtrw=,iv:u/LzwQqaMKt9v0w/qoTMpvzfUfpMz5dVm6ou+yD8xio=,tag:bsL2WabS+NSIrIHNBg0B4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL21NZVJyT0VaQ2hxY2ZJ
            K0xwK2pFdlNJOFUvZVcxWXZVSHIvYUVsblF3CkJBQzJDb2t3Wk12V3hjLzJHMWxz
            TmZFa0xvTzZSMUhyVzB0Mm84d0pQclkKLS0tIEdJc0JiclpjR1l4RUYwbmVQZWl0
            cVhqSDROUjMzOUFaZGIwa0dvSUJ5NWcKyH34AUKxmJDDxCZPj+fexW1O/xp84Adr
            CbHFpV0OCOtfxSRf4mNSeMRaEu8RPlq3W8tMsZKSPVVwzS2umq3/Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-15T12:40:28Z"
    mac: ENC[AES256_GCM,data:xMCl5kgYUJqMqmyYqt3oPd0yMWYAgDG1xPRmnbkwgAoAHtfZmIyt7ek2nK24D0wsOOi8D+Pj25mWraboReOvc94yQBmvT2d82krx2n2SoeBeMfGaJjacAdfsVWxk854TaJHqrLqsFmhBnWqDCZGof0Hspb0HYBYv7xWbLUBQN3o=,iv:XxXIPeE3gYLWvyCO2YdELMn05P+XgRiHM/TJ54CeQ/Y=,tag:AG9WCZoRfBXDIMt62za24Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-prometheus
    namespace: backup
stringData:
    token: ENC[AES256_GCM,data:Cz1L5Q80Iwk=,iv:3LLrLAAGyhxH9E1YSLL4qwraecBRALmBWpggJtcIKic=,tag:SGcfSQMmaaCVNsVbYD4sHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL21NZVJyT0VaQ2hxY2ZJ
            K0xwK2pFdlNJOFUvZVcxWXZVSHIvYUVsblF3CkJBQzJDb2t3Wk12V3hjLzJHMWxz
            TmZFa0xvTzZSMUhyVzB0Mm84d0pQclkKLS0tIEdJc0JiclpjR1l4RUYwbmVQZWl0
            cVhqSDROUjMzOUFaZGIwa0dvSUJ5NWcKyH34AUKxmJDDxCZPj+fexW1O/xp84Adr
            CbHFpV0OCOtfxSRf4mNSeMRaEu8RPlq3W8tMsZKSPVVwzS2umq3/Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-15T12:40:28Z"
    mac: ENC[AES256_GCM,data:xMCl5kgYUJqMqmyYqt3oPd0yMWYAgDG1xPRmnbkwgAoAHtfZmIyt7ek2nK24D0wsOOi8D+Pj25mWraboReOvc94yQBmvT2d82krx2n2SoeBeMfGaJjacAdfsVWxk854TaJHqrLqsFmhBnWqDCZGof0Hspb0HYBYv7xWbLUBQN3o=,iv:XxXIPeE3gYLWvyCO2YdELMn05P+XgRiHM/TJ54CeQ/Y=,tag:AG9WCZoRfBXDIMt62za24Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
