---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
  namespace: backup
spec:
  storageClassName: minio-nfs
  capacity:
    storage: 18T
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NFS_SERVER}"
    path: /mnt/storage/backups/minio
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 2T
