apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:fQ3E7gVXUZzUDGHGhHa1EcyF/5ieIwUt5P00O3o77Gz4waF6aV9INZQbDnwkZVO4xLxVFXI6jhZWp2eW,iv:o8OjZy2njyZ5Hr5NuJBRIO+N21OO6BVF4fLG+KOzFGQ=,tag:2huKHLblY9XvCsttuSS8Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUklZeEhpRGlGWi9aR01o
            S3ozNytsRSs5NUQwWTZUWGhROVJTQmZMU0Y0CmpOeEhBRW9LRFFsZi9SRmYwUDY4
            OU43SDFBWUdTNGZxd29NRVlYQWZpbW8KLS0tIGJUem5haTN1cGt0THVNWGdCVytU
            SWtPVDA4R3NHRjlkV1pVc0Y0Skt0VTQKobXoxkwnpdriNVCIkQxKYx0eGut8o4QY
            hE0ySi5tcAn53fbJgdD0flNvHv5ZNTzWFw8lUiSyDRe40h8l/OnukA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T23:11:21Z"
    mac: ENC[AES256_GCM,data:Xf4LWBqP4y2xI01RmbpRJR4w3PXTr2bKOwraDQF6sesAECHemASYoDUwpJej7VOFBqjc2DmblR9CbjHRKL1lau3SJbNnynKDZSlwa8whT9mRJdGpR61CCqaM9oGEmtUntPP4lQyPYIcDQdaQnHCx4DMQrxSOhDENhsHB2O1NWco=,iv:6cZko/zMPL7aFQ/vCl8VfqFx6g1UnW7FHtX4f6ixIhE=,tag:hLe/agMfKKJjcUDQclrkww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
