apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  commonMetadata:
    labels:
      app.kubernetes.io/name: onepassword-connect
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./kubernetes/apps/external-secrets/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  timeout: 5m
