apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WlK5ozQSM5IOLg==,iv:1MTpf7LlnXLuXKWJqP8R85uDhbE5DHMclM8HB3ihLH8=,tag:9St+Zd6kqzaU2Atgi3rUUw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zP196SnOZULAd1AkD5vdt8R/vyu7uYAtqTlYYXJ1AcaDgg==,iv:QJZlZLyGRP2AyL6DMRwLbFJsqLuKJEyVdJ0/ODtzf4o=,tag:XaLSFj8+Yx444tlKSgIlcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeTRQaitVYjBKV09LbkRJ
            dnF2SmZlUE1lSXB5bE1PNVZIVEhianI5amtrCjRkZkhPdHpJVXpYRTcxb2JzV3Yy
            N09sU3poWElzb2tib1pNbUhMUmxmVUkKLS0tIDZ3T1FZRU9lZGttNTJ5VG1hOTN3
            OUxDMnlSWHc4Yk5nMm05ZXhPd1VFK2cKz3ttA5KBejwUomLzxeAvFBnv2wDyy7+D
            4lu7Rg0zplT0q7r7IziSOOdr9sS0D5V3a8JGQFp88Lc8mud6Hael1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T21:26:42Z"
    mac: ENC[AES256_GCM,data:fP1a+uFQokw4o6Lqkg5aRBjzwouYoyRdR9qW2cbYuyeJ8QQeszUdqINpH7QHS0+eCGeAlIRvPSQCzfA0wBsEFKbMirdgdrh4S9lCDOB/dGtVsAy3XSu/GW4oZuG7QYLho03O1zHh50FG7upTfTjhjWMNMZ78URFxaobm0NShHu4=,iv:U/3gMefNC4+0Www4prM4gAAW2Gu4teiWQwJw5CVqO+k=,tag:Rsjp3xvRNeUSjxtxRGOAvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
