apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:i7zmL32CzObu6w==,iv:QfZDkAPlKr93ZIyAFF7Yxp02RQ7QlF+T1JNuySAH4Q8=,tag:jWoPKcR+cnTj18IUdEci6Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qMxGrf/xv934JOhaj1JPKfkJMkCXjPpykPJA9eI2aRK9Qw==,iv:Bh7qZsBp5dH0LCc2/XsNyv8vk41QyDY2LDWr60N7Pig=,tag:hkHvR4fJ4+ZrexptZnRyeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWFE2eVJNQ0hFd01ZcGRM
            Q1NBWVV4RDNtQVJQREorZkJGQUpYeFBVOGxVCmlvRnV6UzYyRTlrUUlid244QWM3
            d3dEcE9hSUpXeDY4RjM1bDRmQkQ1c2cKLS0tIHk3ZURIMFBRVDJrOGM0VjQ0ZEJP
            UUdVc1BBbEtsMC9tcmRUNExjNVZIM2MKgv4s0CeQ0pRfQ5agtMn6yPZrsgWYJRfL
            GYhs72pFD6E9of+mHolZvosJtg3LIyuj3dcO0sJnL9JYC3wkvgXzwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T17:19:30Z"
    mac: ENC[AES256_GCM,data:7fIKWHf3v7h3vSHtjFKRJhzgIAnjbQ20LeS6BytcpzH5dOMeZyPS2Mi9H1CaFD6qoTZYertlJ9X4bAoaNsrUw7H2HTcQj5lXbctTz+wfiW9HJhgV7m9kVybzX7ZVIBipCxuMDjlg7GMoBGtlZOhDFh1wPwLS0m/Y5UVKot8BH5o=,iv:x622cwOMNe4R2jyy/gSLtNxRPUJjOS69gfadMWWc5UY=,tag:b6+uzqauClLMrW36q349UA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
