---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Andorra"
  KUBE_VIP_ADDR: "192.168.1.245"
  METALLB_LB_RANGE: "192.168.1.220-192.168.1.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.220"
  METALLB_INGRESS_ADDR: "192.168.1.221"
  SVC_POSTGRES_ADDR: "192.168.1.240"
