---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Andorra"
  KUBE_VIP_ADDR: "192.168.1.245"
  NETWORK_K8S_CLUSTER_CIDR: "10.0.0.0/8"
  METALLB_LB_RANGE: "192.168.1.220-192.168.1.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.220"
  METALLB_INGRESS_ADDR: "192.168.1.221"
  SVC_POSTGRES_ADDR: "192.168.1.240"
  SVC_REDIS_ADDR: "192.168.1.241"

  ROUTER_IP: "192.168.1.1"
  DNS_IP: "192.168.1.11"

  # NFS
  NFS_SERVER: "192.168.1.3"
  NFS_BASE_PATH: "/mnt/storage"
