apiVersion: v1
kind: Secret
metadata:
    name: thanos-secret
    namespace: monitoring
stringData:
    S3_BUCKET_NAME: ENC[AES256_GCM,data:8SPYvU8J,iv:sq+KUdbUoxVdVXLOc830ANJT+2AipXQGl23Z7quU3VA=,tag:XGorLNLAIrQp5+hr/jPdFA==,type:str]
    S3_BUCKET_HOST: ENC[AES256_GCM,data:MHAZ/1/LPumGO99ZM0lE6YabSg==,iv:ZRpmQcgZA92nonnVXoMU+Wusw+hcHU4cV9zD7gnHJBU=,tag:Menw0rljznWmnYj2lm5mZg==,type:str]
    S3_BUCKET_REGION: ""
    S3_ACCESS_KEY: ENC[AES256_GCM,data:OW/zMx8=,iv:u4RVYJT0AAQ9svUyU4anPw40jPBc2BBDIadltvjYxsg=,tag:dTSWhGUZcC6hBG92mCJgDg==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:isAOrk8LXR+e7TWKcdyi/PGXt8VcYGzEILPtBsUg02Y=,iv:0B5l8VIpJLzokIZ33+I9Q8KgcJMfFXXrNyE5Bf4sbgw=,tag:VBYD1AGEq7DtC2XtABLezg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10gnws2l65p2yk0sxceykm8zlauxmg0tgz370c77dq2jjf24tnfusw65lr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL21NZVJyT0VaQ2hxY2ZJ
            K0xwK2pFdlNJOFUvZVcxWXZVSHIvYUVsblF3CkJBQzJDb2t3Wk12V3hjLzJHMWxz
            TmZFa0xvTzZSMUhyVzB0Mm84d0pQclkKLS0tIEdJc0JiclpjR1l4RUYwbmVQZWl0
            cVhqSDROUjMzOUFaZGIwa0dvSUJ5NWcKyH34AUKxmJDDxCZPj+fexW1O/xp84Adr
            CbHFpV0OCOtfxSRf4mNSeMRaEu8RPlq3W8tMsZKSPVVwzS2umq3/Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-16T19:11:31Z"
    mac: ENC[AES256_GCM,data:sUVuo5oINxMafwWYSlQDu50PtzNQjFbK70Vx9IObON7GgvczSRjwZ39+B8nmIWdGKKK7BgbvAu9NVqoi1BoPM3m+M2cyBVynG6kkmgsiyVkVAaLibDGqb7Ngi4PiLshw12EcuGGnjPYXgUbaJknxEnxqeAChr/i76yx28OSJ8lk=,iv:VEA6m5vYDg0fwgIiFovUbjfW2A9YmelR76jvunCgy60=,tag:vyfWqeIOZy2u3kGS9KcuGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
