# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: network
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: network
  values:
    controllers:
      cloudflare-ddns:
        containers:
          app:
            image:
              repository: timothyjmiller/cloudflare-ddns
              tag: 2.1.2
            env:
              CLOUDFLARE_API_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-ddns-token
                    key: api-token
              IP4_DOMAINS: flux-webhook.stasky.win,wg.stasky.win
              DELETE_ON_FAILURE: false
              RECORD_COMMENT: CF_DDNS
              MANAGED_RECORDS_COMMENT_REGEX: CF_DDNS

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
