apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: "192.168.42.100"
      stop: "192.168.42.200"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
